//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.STS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="STS.IMySTS")]
    public interface IMySTS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySTS/DoSomething", ReplyAction="http://tempuri.org/IMySTS/DoSomethingResponse")]
        int DoSomething();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySTS/DoSomething", ReplyAction="http://tempuri.org/IMySTS/DoSomethingResponse")]
        System.Threading.Tasks.Task<int> DoSomethingAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMySTSChannel : Client.STS.IMySTS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MySTSClient : System.ServiceModel.ClientBase<Client.STS.IMySTS>, Client.STS.IMySTS {
        
        public MySTSClient() {
        }
        
        public MySTSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MySTSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MySTSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MySTSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int DoSomething() {
            return base.Channel.DoSomething();
        }
        
        public System.Threading.Tasks.Task<int> DoSomethingAsync() {
            return base.Channel.DoSomethingAsync();
        }
    }
}
